### ISSUE TITLE
uHTTP::body() don't return full data

### ISSUE THREAD

**Issue by NitrofMtl** [nomadnt/uHTTP#13]
Hi.

I run uHTTP on my arduino, everything work execpt if I want to get data from body.
on a put request , the client send json data, if a print client all the data is present a have a size of approximatly 1500 char.

but even if I push the uHTTP_buffer_size to 2000 or 3000, the body() return only a faction of the data.

this is client request: 
     UT /channels HTTP/1.1
    Host: 192.168.0.110
    Connection: keep-alive
    Content-Length: 1511
    Accept: application/json, text/plain, */*
    Origin: http://192.168.0.110
    User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko)              Chrome/46.0.2490.80 Safari/537.36
    Content-Type: application/json;charset=UTF-8
    Referer: http://192.168.0.110/
    Accept-Encoding: gzip, deflate, sdch
     Accept-Language: en-US,en;q=0.8,fr;q=0.6
      {"channels":"[{\"name\":\"name0\",\"canal\":\"0\",\"status\":true,\"temperature\":21.42,\"setPoint\":5,\"permission\":false,\"percentOut\":0,\"$$hashKey\":\"0YJ\"},{\"name\":\"name1\",\"canal\":\"1\",\"status\":false,\"temperature\":-50,\"setPoint\":5,\"permission\":false,\"percentOut\":0,\"$$hashKey\":\"0YK\"},{\"name\":\"name2\",\"canal\":\"2\",\"status\":false,\"temperature\":0,\"setPoint\":5,\"permission\":false,\"percentOut\":0,\"$$hashKey\":\"0YL\"},{\"name\":\"name3\",\"canal\":\"3\",\"status\":false,\"temperature\":0,\"setPoint\":5,\"permission\":false,\"percentOut\":0,\"$$hashKey\":\"0YM\"},{\"name\":\"name4\",\"canal\":\"4\",\"status\":false,\"temperature\":21.27,\"setPoint\":5,\"permission\":false,\"percentOut\":0,\"$$hashKey\":\"0YN\"},{\"name\":\"name5\",\"canal\":\"5\",\"status\":false,\"temperature\":20.88,\"setPoint\":5,\"permission\":false,\"percentOut\":0,\"$$hashKey\":\"0YO\"},{\"name\":\"name6\",\"canal\":\"6\",\"status\":false,\"temperature\":21.01,\"setPoint\":5,\"permission\":false,\"percentOut\":0,\"$$hashKey\":\"0YP\"},{\"name\":\"name7\",\"canal\":\"7\",\"status\":false,\"temperature\":21.04,\"setPoint\":5,\"permission\":false,\"percentOut\":0,\"$$hashKey\":\"0YQ\"},{\"name\":\"name8\",\"canal\":\"8\",\"status\":false,\"temperature\":-50,\"setPoint\":5,\"permission\":false,\"percentOut\":0,\"$$hashKey\":\"0YR\"},{\"name\":\"name9\",\"canal\":\"9\",\"status\":false,\"temperature\":-50,\"setPoint\":5,\"permission\":false,\"percentOut\":0,\"$$hashKey\":\"0YS\"}]"}-50,\"setPoint\":5,\"permission\":false,\"percentOut\":0,\"$$hashKey\":\"0YR\"},{\"name\":\"name9\",\"canal\":\"9\",\"status\":false,\"temperature\":-50,\"setPoint\":5,\"permission\":false,\"percentOut\":0,\"$$hashKey\":\"0YS\"}]"}

**Comment by tonyputi** [comment]
Hi, in according to [uHTTP.h](https://github.com/nomadnt/uHTTP/blob/master/uHTTP.h#L39) and [uHTTP.cpp](https://github.com/nomadnt/uHTTP/blob/master/uHTTP.cpp#L169-L172) you should change uHTTP_BODY_SIZE value and not uHTTP_BUFFER_SIZE value.

Regards

**Comment by NitrofMtl** [comment]
oups I wrote here the wrong one...  a tried with the body size. it did'nt work

**Comment by tonyputi** [comment]
Ok, thanks. I'll check as soon as possible.

Regards

**Comment by NitrofMtl** [comment]
Found the solution.
to use  uHTTP_BODY_SIZE greater than 255, you have to change, in:
     EthernetClient uHTTP::available()

the variable declaration:
    uint8_t cursor = 0

to uint16_t cursor = 0 

Regards

**Comment by tonyputi** [comment]
Perfect. Thank you!
Il 11/Dic/2015 02:43, "NitrofMtl" <notifications@github.com> ha scritto:
